name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build AmazTimer
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with: 
        args: "./gradlew assembleDebug"
